// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vplnxxpdfevhxddffcrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbG54eHBkZmV2aHhkZGZmY3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODQ1ODMsImV4cCI6MjA2NTU2MDU4M30.eqqnwPJzgk8Qp_Ek9_V7WkqlOpWZSf9M8r2YeEFXP5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);